
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.jbpm.ws.example.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Nov 18 17:04:29 EST 2014
 * Generated source version: 2.2.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldServiceImplV1",
                      portName = "HelloWorldServiceImplV1Port",
                      targetNamespace = "http://v1.example.ws.jbpm.org/",
                      wsdlLocation = "http://localhost:8080/example-ws-secure/HelloWorldServiceImplV1?wsdl",
                      endpointInterface = "org.jbpm.ws.example.v1.HelloWorldService")
                      
public class HelloWorldServiceImpl implements HelloWorldService {

    private static final Logger LOG = Logger.getLogger(HelloWorldServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.jbpm.ws.example.v1.HelloWorldService#sayHello(java.lang.String  name )*
     */
    public java.lang.String sayHello(java.lang.String name) { 
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
