package org.jbpm.ws.example.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Nov 18 17:04:29 EST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://v1.example.ws.jbpm.org/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://v1.example.ws.jbpm.org/", className = "org.jbpm.ws.example.v1.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://v1.example.ws.jbpm.org/", className = "org.jbpm.ws.example.v1.SayHelloResponse")
    @WebMethod
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
