
/*
 * 
 */

package org.jbpm.ws.example.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Nov 18 17:04:29 EST 2014
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "HelloWorldServiceImplV1", 
                  wsdlLocation = "http://localhost:8080/example-ws-secure/HelloWorldServiceImplV1?wsdl",
                  targetNamespace = "http://v1.example.ws.jbpm.org/") 
public class HelloWorldServiceImplV1 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://v1.example.ws.jbpm.org/", "HelloWorldServiceImplV1");
    public final static QName HelloWorldServiceImplV1Port = new QName("http://v1.example.ws.jbpm.org/", "HelloWorldServiceImplV1Port");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/example-ws-secure/HelloWorldServiceImplV1?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/example-ws-secure/HelloWorldServiceImplV1?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldServiceImplV1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldServiceImplV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldServiceImplV1() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServiceImplV1Port")
    public HelloWorldService getHelloWorldServiceImplV1Port() {
        return super.getPort(HelloWorldServiceImplV1Port, HelloWorldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServiceImplV1Port")
    public HelloWorldService getHelloWorldServiceImplV1Port(WebServiceFeature... features) {
        return super.getPort(HelloWorldServiceImplV1Port, HelloWorldService.class, features);
    }

}
